services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./prisma:/app/prisma
      - sqlite_data:/app/prisma
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}

volumes:
  sqlite_data:
